[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_program = "75Y6LyCnaUGwWu7GyDkVTrYBdDw9USyYRkoqEx9Xd43c"

[programs.devnet]
anchor_program = "75Y6LyCnaUGwWu7GyDkVTrYBdDw9USyYRkoqEx9Xd43c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/aadelop/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
